[project]
name = "ind320-project-kristianrohne"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kristian Mathias Røhne", email = "kristian.mathias.rohne@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "streamlit>=1.64.0",
]

[project.scripts]
ind320-project-kristianrohne = "ind320_project_kristianrohne:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
